student_portal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from authentication.views import HomeView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('expenses/',include('expenses.urls',namespace='expenses')),
    path('accounts/',include('authentication.urls',namespace='authentication')),
    path('settings/',include('settings.urls',namespace='settings')),
    path('income/',include('income.urls',namespace='income')),
    path('profile/',include('profiles.urls',namespace='profile')),
    path('notes/',include('notes.urls',namespace='notes')),
    path('todo/',include('todo.urls',namespace='todo')),
    path('youtube/',include('youtube.urls',namespace='youtube')),
    path('books/',include('books.urls',namespace='books')),
    path('wikipedia/',include('wiki.urls',namespace='wikipedia')),
    path('dictionary/',include('dictionary.urls',namespace='dictionary')),
   
    path('',HomeView,name='home'),
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path
from .views import TodoListView,TodoCreateView,TodoUpdateView,TodoDeleteView,TodoEditView

app_name = 'todo'

urlpatterns = [
    
    path('all-todo/',TodoListView.as_view(),name='all-todos'),
    path('create-todo/',TodoCreateView.as_view(),name='create-todo'),
    path('edit-todo/<slug>/',TodoEditView,name='edit-todo'),
    path('update-todo/<slug>/',TodoUpdateView,name='update-todo'),
    path('delete-todo/<slug>/',TodoDeleteView,name='delete-todo'),
    
]

todo/models.py
from django.db import models
from profiles.models import Profile
from django.core.exceptions import ValidationError
from autoslug import AutoSlugField
# Create your models here.
class Todo(models.Model):
    task = models.CharField(max_length=60)
    completed = models.BooleanField(default=False)
    owner = models.ForeignKey(Profile,on_delete=models.CASCADE)
    slug  = AutoSlugField(populate_from='task',unique_with=['owner','created'])
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return str(self.task) + ' todo ' + str(self.owner)
    
    class Meta:
        ordering = ['-created']
        verbose_name = 'Todo'
        verbose_name_plural = 'Todo'
        unique_together = ('task','owner')
        
    def validate_unique(self,exclude=None):
        try:
            super(Todo,self).validate_unique()
        except ValidationError as e:
            raise ValidationError("Oops, this todo item already exists")
    
   

todo/forms.py
from django.forms import ModelForm 
from .models import Todo

class TodoForm(ModelForm):
    
    class Meta:
        model = Todo
        fields = ['task','completed']
    
    def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['task'].widget.attrs.update({'class': 'form-control'})
            #self.fields['completed'].widget.attrs.update({'class': 'form-control'})

todo/views.py
from django.http.response import Http404
from django.views.generic import ListView,DetailView,UpdateView
from django.views.generic.edit import CreateView, DeleteView
from .models import Todo
from .forms import TodoForm
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse,reverse_lazy
from django.shortcuts import get_object_or_404, redirect,render
from django.views.decorators.http import require_http_methods



# Create your views here.
class TodoListView(LoginRequiredMixin,ListView):
    model = Todo
    template_name= 'todo.html'
    context_object_name = 'all_todos'
    paginate_by = 10

    def get_queryset(self):
        all_todos = Todo.objects.filter(owner=self.request.user.profile)
        return all_todos

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = TodoForm()
        context['form'] = form
        return context

 
def TodoEditView(request,slug,*args, **kwargs):
    todo_item = Todo.objects.get(slug=str(slug),owner=request.user.profile)
    form = TodoForm(instance=todo_item)
    if request.method == 'POST':
        form = TodoForm(request.POST or None,instance=todo_item)
        if form.is_valid():
            form.save()
            messages.success(request,'todo item was successfully updated')
            return redirect('todo:all-todos')
        else:
            messages.error(request,'sorry, an error occured your todo item was not update')
            return render(request,'todo-edit.html',{'form':form})
    else:
        return render(request,'todo-edit.html',{'form':form,'todo':todo_item})
            
    

    

class TodoCreateView(LoginRequiredMixin,SuccessMessageMixin,CreateView):
    model = Todo
    form_class = TodoForm
    success_url = reverse_lazy('todo:all-todos')
    success_message = 'Todo-Item was successfully created'
    template_name = 'create-todo.html'
    
    def form_valid(self, form):
        self.instance = form.save(commit=False)
        self.instance.owner = self.request.user.profile
        self.instance.save()
        return super().form_valid(form)
    
    
@require_http_methods('POST')
def TodoDeleteView(request,slug,*args, **kwargs):
    todo_item = Todo.objects.get(slug=str(slug),owner=request.user.profile)
    messages.success(request, "todo was deleted sucessfully")
    todo_item.delete()
    return redirect('todo:all-todos')


@require_http_methods('POST')
def TodoUpdateView(request,slug,*args, **kwargs):
    """Helps user check for completed or non completed task"""
    todo_item = Todo.objects.get(slug=str(slug),owner=request.user.profile)
    if todo_item.completed == True:
        todo_item.completed = False 
        todo_item.save()
    else:
        todo_item.completed = True
        todo_item.save()
    return redirect('todo:all-todos')

todo/templates/todo-edit.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
 Edit Todo
{% endblock title %}
{% block content %}

<style>
    .errorlist{
        margin-bottom:4px;
        padding: 0px;
        list-style-type:none;
        font-weight: 500;
        color: red;
      }
    .nav-add-action {
        display: flex;
        justify-content: space-between;
    }
</style>

    <div class="pagetitle">
        <nav class="nav-add-action">
           <div >
            <h1>Update Note</h1>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
                <li class="breadcrumb-item active">Update Todo</li>
            </ol>
        </div>
        <div class="add-action-div">
           
        </div>
        </nav>
    </div><!-- End Page Title -->
    {% include 'partials/_messages.html' %}
    <form  class="form-group" method="POST" >
        {% csrf_token %}
        {{form.as_p}}
       <div class="mt-3 text-center">
        <button type="submit" class="btn button-background">Update Todo</button>
       </div>
    </form>
    


{% endblock content %}

todo/templates/todo.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Todo
{% endblock title %}
{% block content %}

<style>
    .errorlist {
        margin-bottom: 4px;
        padding: 0px;
        list-style-type: none;
        font-weight: 500;
        color: red;
    }
    form{
        margin-right: 3px !important;
    }

    .nav-add-action {
        display: flex;
        justify-content: space-between;
    }
</style>

<div class="pagetitle">
    <nav class="nav-add-action">
        <div>
            <h1>Todo</h1>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
                <li class="breadcrumb-item active">Todo</li>
            </ol>
        </div>
        <div class="add-action-div">

        </div>
    </nav>
</div><!-- End Page Title -->
{% include 'partials/_messages.html' %}
<div class="card">

    <div class="card-body">
        <div class="container mt-4">
            <form action="{% url 'todo:create-todo' %}" class="form-group" method="POST" style="display: flex;">
                {% csrf_token %}
                {{form.task}}
                <div class="text-center">
                    <button type="submit" class="btn button-background btn-lg">+</button>
                </div>
            </form>
        </div>

        <div class="container mt-4">
            {% if all_todos %}

            <div class="card">
                <ul class="list-group list-group-flush">
                    {% for todo in all_todos  %}
                    <div class="list-group-item" style="display: flex;justify-content:space-between;align-items:center;">
                        {% if todo.completed %}
                        <div class="text-decoration-line-through" style="display: flex;justify-content:space-between;align-items:center;font-size:small;"> 
                            {{todo.task}}
                        </div>
                        {% else %}
                        <div style="display: flex;justify-content:space-between;align-items:center;font-size:small;"> 
                            {{todo.task}}
                        </div>
                        {% endif %}
                        
                        <div>
                            <div style="display: flex;justify-content:space-around;">
                                <form action="{% url 'todo:update-todo' todo.slug %}" class="form-group" method="POST"
                                    style="display: flex;height:inherit;">
                                    {% csrf_token %}
                                    {% if todo.completed %}
                                    <button class="btn btn-danger btn-sm">
                                        <i class="bi bi-check-lg"></i>
                                    </button>
                                    {% else %}
                                    <button class="btn btn-primary btn-sm">
                                        <i class="bi bi-check-lg"></i>
                                    </button>
                                    {% endif %}
                                </form>
                                <form action="{% url 'todo:edit-todo' todo.slug %}" class="form-group" method="GET"
                                    style="display: flex;">
                                    {% csrf_token %}
                                    <button class="btn btn-success btn-sm"><i class="bi bi-pen"></i></button>
                                </form>
                                <form action="{% url 'todo:delete-todo' todo.slug %}" class="form-group" method="POST"
                                    style="display: flex;">
                                    {% csrf_token %}
                                    <button class="btn btn-secondary btn-sm"><i class="bi bi-x-octagon-fill"></i></button>
                                </form>
                            </div>
                        </div>

                    </div>
                    {% endfor %}
                </ul>
            </div>

            {% else %}
            <div class="alert alert-info" role="alert">
                No todo item available create one
            </div>
            {% endif %}
        </div>
    </div>
</div>



{% endblock content %}