expenses/urls.py
from django.urls import path
from .views import (
    ExpenseView,AddExpenseView,UpdateExpenseView,
    DeleteExpenseView,SearchExpenses,expense_category_summary_json,ViewExpenseSummary,search_by_date,
    search_within_date_range,export_csv,export_pdf,ExpenseCategoryView,UpdateExpenseCategoryView
    ,AddExpenseCategoryView,DeleteExpenseCategoryView
    )

app_name = 'expenses'

urlpatterns = [

    
    path('',ExpenseView.as_view(),name='expenses'),
    path('add-expense/',AddExpenseView.as_view(),name='add-expenses'),
    path('search-expenses/',SearchExpenses,name='search-expenses'),
    path('update-expense/<slug>/',UpdateExpenseView.as_view(),name='update-expense'),
    path('delete-expense/<slug>/',DeleteExpenseView.as_view(),name='delete-expense'),
    path('expense-summary-json/',expense_category_summary_json,name='expense-category-summary-json-name'),
    path('expense-category-summary-/',ViewExpenseSummary.as_view(),name='expense-summary'),
    path('search-by-date/',search_by_date,name='search-by-date'),
    path('search-within-date/',search_within_date_range,name='search-within-date'),
    path('export-csv/',export_csv,name='export-csv'),
    path('export-pdf/',export_pdf,name='export-pdf'),
    
    
    path('categories/',ExpenseCategoryView.as_view(),name='expense-categories'),
    path('add-expense-category/',AddExpenseCategoryView.as_view(),name='add-expense-category'),
    path('update-expense-category/<slug>/',UpdateExpenseCategoryView.as_view(),name='update-expense-category'),
    path('delete-expense-category/<slug>/',DeleteExpenseCategoryView.as_view(),name='delete-expense-category'),    
]

student_portal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from authentication.views import HomeView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('expenses/',include('expenses.urls',namespace='expenses')),
    path('accounts/',include('authentication.urls',namespace='authentication')),
    path('settings/',include('settings.urls',namespace='settings')),
    path('income/',include('income.urls',namespace='income')),
    path('profile/',include('profiles.urls',namespace='profile')),
    path('notes/',include('notes.urls',namespace='notes')),
    path('todo/',include('todo.urls',namespace='todo')),
    path('youtube/',include('youtube.urls',namespace='youtube')),
    path('books/',include('books.urls',namespace='books')),
    path('wikipedia/',include('wiki.urls',namespace='wikipedia')),
    path('dictionary/',include('dictionary.urls',namespace='dictionary')),
   
    path('',HomeView,name='home'),
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path
from .views import TodoListView,TodoCreateView,TodoUpdateView,TodoDeleteView,TodoEditView

app_name = 'todo'

urlpatterns = [
    
    path('all-todo/',TodoListView.as_view(),name='all-todos'),
    path('create-todo/',TodoCreateView.as_view(),name='create-todo'),
    path('edit-todo/<slug>/',TodoEditView,name='edit-todo'),
    path('update-todo/<slug>/',TodoUpdateView,name='update-todo'),
    path('delete-todo/<slug>/',TodoDeleteView,name='delete-todo'),
    
]

expenses/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from autoslug import AutoSlugField



class ExpenseCategory(models.Model):
    name = models.CharField(max_length=255)
    owner = models.ForeignKey(User,on_delete=models.CASCADE)
    slug  = AutoSlugField(populate_from='name',unique_with=['created'])
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name='Category'
        verbose_name_plural='Category'
        unique_together = ('name','owner')
    
    def __str__(self):
        return str(self.name)
    
    def validate_unique(self,exclude=None):
        try:
            super(ExpenseCategory,self).validate_unique()
        except ValidationError as e:
            raise ValidationError("Ooops, "+ str(self.name)+" expense category already exists ")

    
    
class Expense(models.Model):
    owner = models.ForeignKey(User,on_delete=models.CASCADE)
    description = models.CharField(max_length=800)
    slug  = AutoSlugField(populate_from='description',unique_with=['owner','category','created','updated'],unique=True)
    amount = models.FloatField(validators=[MinValueValidator(limit_value=0,message="sorry your expenses can't be less than zero")])
    expense_date = models.DateField(help_text='yyyy-mm-dd')
    category = models.ForeignKey(ExpenseCategory,on_delete=models.CASCADE) 
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-expense_date']
        unique_together = ('amount','description','category','owner')
    
    def get_category(self):
        return self.category
    
    def __str__(self):
        return str(self.owner) + ' ' +str(self.category) + ' expenses' 
    
    def validate_unique(self,exclude=None):
        try:
            super(Expense,self).validate_unique()
        except ValidationError as e:
            raise ValidationError("Ooops," + str(self.amount)+ " with same description and category already exists")
    
    

    

    

expenses/forms.py
from django.forms import ModelForm
from .models import Expense,ExpenseCategory 
from django import forms 

class ExpenseForm(ModelForm):
    
    class Meta:
        model = Expense
        fields = ['description','amount','expense_date','category']
        
    def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            
            self.fields['description'].widget.attrs.update({'class': 'form-control'})
            self.fields['amount'].widget.attrs.update({'class': 'form-control'})
            self.fields['category'].widget.attrs.update({'class': 'form-control'})
            self.fields['expense_date'].widget.attrs.update({'class': 'form-control','type':'date'})
            
class ExpenseCategoryForm(ModelForm):
    
    class Meta:
        model=ExpenseCategory
        fields = ['name']
    
    def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['name'].widget.attrs.update({'class': 'form-control'})
    
    

expenses/views.py
from django.contrib.auth.models import User
from django.http import JsonResponse, request,Http404
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic import ListView,CreateView,UpdateView,DeleteView,TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import ExpenseCategory, Expense
from django.contrib import messages
from .forms import ExpenseForm,ExpenseCategoryForm
from django.urls import reverse_lazy,reverse
from django.contrib.messages.views import SuccessMessageMixin
from django.views.decorators.http import require_http_methods
from settings.models import UserPreferences
from django.contrib.auth.decorators import login_required
import datetime,csv,json
# Create your views here.
  
class ExpenseView(LoginRequiredMixin,ListView):
    """This View lists all the expenses a user incures"""
    model = Expense
    template_name = 'expenses.html'
    context_object_name = 'expenses' 
    paginate_by = 5
    
    def get_queryset(self):
        expenses = Expense.objects.filter(owner=self.request.user)
        return expenses 
         

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # get currency of user
        currency = UserPreferences.objects.get(user=self.request.user)
        context['currency'] = currency
        
        return context
    
    

class AddExpenseView(LoginRequiredMixin,CreateView):
    """This View helps users to add expense"""
    model = Expense
    form_class = ExpenseForm
    template_name='add-expense.html'
    
    def get_context_data(self, **kwargs):
        context =  super(AddExpenseView,self).get_context_data(**kwargs)
        context['form'].fields['category'].queryset = ExpenseCategory.objects.filter(owner=self.request.user)
        return context
    
   

    
    def post(self,request,*args, **kwargs):
        form = ExpenseForm(request.POST or None)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.owner = request.user
            form.save()
            messages.success(request,'Expense has been added succesfully')
            return redirect('expenses:expenses')
        else:
            messages.error(request,'Sorry, your expense could not be added due to an errror')
            return render(request,'add-expense.html',{'form':form})
        
 
    
    
class UpdateExpenseView(LoginRequiredMixin,SuccessMessageMixin,UpdateView):
    """This View helps user Update their expenses"""
    model = Expense
    form_class = ExpenseForm
    template_name = 'update-expense.html' 
    success_message = "Expense was updated sucessfully"
    success_url =  reverse_lazy('expenses:expenses') 
    
    def get_context_data(self, **kwargs):
        context =  super(UpdateExpenseView,self).get_context_data(**kwargs)
        context['form'].fields['category'].queryset = ExpenseCategory.objects.filter(owner=self.request.user)
        return context
    
    def get_object(self, queryset=None):
        """ Hook to ensure object is owned by request.user. """
        obj = super(UpdateExpenseView, self).get_object()
        if not obj.owner == self.request.user:
            raise Http404
        return obj

    
   
    
class DeleteExpenseView(LoginRequiredMixin,DeleteView):
    """This view helps users delete expenses"""
    model = Expense
    success_url = reverse_lazy('expenses:expenses') 
    
    def get_success_url(self):
        messages.success(self.request,"Expense was deleted sucessfully")
        return reverse('expenses:expenses') 
    
    def get_object(self, queryset=None):
        """ Hook to ensure object is owned by request.user. """
        obj = super(DeleteExpenseView, self).get_object()
        if not obj.owner == self.request.user:
            raise Http404
        return obj


@login_required
@require_http_methods('POST')
def SearchExpenses(request):
    """This view helps user to search for expense by category"""
    search_str = json.loads(request.body).get('searchText') 
    expensecategory = ExpenseCategory.objects.filter(name__icontains=search_str)
    expenses = Expense.objects.filter(category__in=expensecategory,owner=request.user)
    data = expenses.values()
    return JsonResponse(list(data), safe=False)
    
@login_required
@require_http_methods('POST')   
def expense_category_summary_json(request):
    """Generates expense total amount based on category for expense summary page by default"""
    todays_date = datetime.date.today()
    six_months_ago = todays_date - datetime.timedelta(days=180)
    expenses = Expense.objects.filter(expense_date__gte=six_months_ago,expense_date__lte = todays_date,owner=request.user)
    finalrep = {}
    
    for expense in expenses:
       if  finalrep.get(expense.category.name) is not None:
           finalrep[expense.category.name]+= expense.amount
       else:
           finalrep[expense.category.name] = expense.amount
    return JsonResponse({'expense_category_data':finalrep},safe=False)


class ViewExpenseSummary(LoginRequiredMixin,TemplateView):
    """This is the default view for the expense summary page"""
    template_name = "expense-stats.html" 

@login_required
@require_http_methods('POST') 
def search_by_date(request):
    """This view helps user to search for expense incurred on a specific date"""
    date = json.loads(request.body).get('date')     
    expenses = Expense.objects.filter(expense_date=date,owner=request.user)
    finalrep = {}
    for expense in expenses:
       if  finalrep.get(expense.category.name) is not None:
           finalrep[expense.category.name]+= expense.amount
       else:
           finalrep[expense.category.name] = expense.amount
    return JsonResponse({'expense_category_data':finalrep},safe=False)


@require_http_methods('POST')
def search_within_date_range(request):
    """This view helps users search for expenses incurred with a date range eg from 2/22/2021 to current day"""
    date = json.loads(request.body).get('date')     
    todays_date = todays_date = datetime.date.today()
    expenses = Expense.objects.filter(expense_date__gte=date,expense_date__lte = todays_date,owner=request.user)
    finalrep = {}
    
    for expense in expenses:
       if  finalrep.get(expense.category.name) is not None:
           finalrep[expense.category.name]+= expense.amount
       else:
           finalrep[expense.category.name] = expense.amount
    return JsonResponse({'expense_category_data':finalrep},safe=False)

@login_required
@require_http_methods('GET')
def export_csv(request):
    """This view helps user to export expenses data as csv"""
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename=expenses'+str(request.user.username)+str(datetime.datetime.now())+'.csv'
    writer = csv.writer(response)
    writer.writerow(['Description','Category','Amount','Date'])
    
    expenses = Expense.objects.filter(owner=request.user)
    
    for expense in expenses:
        writer.writerow([expense.description,expense.category,expense.amount,expense.expense_date])
    return response


@login_required
@require_http_methods('GET')
def export_pdf(request,*args, **kwargs):
    """This view helps users to export expenses data as pdf"""
    expenses = Expense.objects.filter(owner=request.user)
    currency = UserPreferences.objects.get(user=request.user)
    return render(request,'expense-pdf-output.html',context={'expenses':expenses,'currency':currency})



#------------------------------------Income Sources-----------------------------------------------
class ExpenseCategoryView(LoginRequiredMixin,ListView):
    """Lets users view all their income sources"""
    model = ExpenseCategory
    template_name = 'expense-category/expense-category.html' 
    paginate_by = 5
    context_object_name = 'expense_categories' 
    
    def get_queryset(self):
        # Get income  sources queryset
        expense_categories =ExpenseCategory.objects.filter(owner=self.request.user)
        return expense_categories
        
class AddExpenseCategoryView(LoginRequiredMixin,CreateView):
    form_class =ExpenseCategoryForm
    template_name='expense-category/add-expense-category.html'
    
    
   
    
    def post(self,request,*args, **kwargs):
        form =ExpenseCategoryForm(request.POST or None)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.owner = request.user
            form.save()
            messages.success(request,'Expense category has been added succesfully')
            return redirect('expenses:expense-categories')
        else:
            messages.error(request,'Sorry, your expense category could not be added due to an errror')
            return render(request,'expense-category/add-expense-category.html',{'form':form})
            
            
class UpdateExpenseCategoryView(LoginRequiredMixin,SuccessMessageMixin,UpdateView):
    model = ExpenseCategory
    form_class = ExpenseCategoryForm
    template_name = 'expense-category/update-expense-category.html'
    success_message = "Expense category was updated sucessfully"
    success_url =  reverse_lazy('expenses:expense-categories') 
    
    def get_object(self, queryset=None):
        """ Hook to ensure object is owned by request.user. """
        obj = super(UpdateExpenseCategoryView, self).get_object()
        if not obj.owner == self.request.user:
            raise Http404
        return obj
    

class DeleteExpenseCategoryView(LoginRequiredMixin,SuccessMessageMixin,DeleteView):
    model =ExpenseCategory
    success_url = reverse_lazy('expenses:expense-categories') 
    
    def get_success_url(self):
        messages.success(self.request, "Expense category was deleted sucessfully")
        return reverse('expenses:expense-categories')
    
    def get_object(self, queryset=None):

expenses/templates/add-expense.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Add expenses
{% endblock title %}

{% block content %}
<style>
    .errorlist{
        margin-bottom:4px;
        padding: 0px;
        list-style-type:none;
        font-weight: 500;
        color: red;
      }
</style>

    <div class="pagetitle">
        <h1>Add Expense</h1>
        <nav >
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
                <li class="breadcrumb-item active">Add Expense </li>
            </ol>
        </nav>
    </div><!-- End Page Title -->
    {% include 'partials/_messages.html' %}
    
    <form action="{% url 'expenses:add-expenses' %}" class="form-group" method="POST" >
        {% csrf_token %}
        {{form.as_p}}
       <div class="mt-3 text-center">
        <button type="submit" class="btn button-background">Add Expense</button>
       </div>
    </form>
    


{% endblock content %}

expenses/templates/expense-pdf-output.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Expenses File PDF View</title>

    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/expenses-download-as-pdf.js' %}"></script>
    <script src="{% static 'assets/js/html2pdf.bundle.min.js' %}"></script>
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/pdf-output.css' %}" rel="stylesheet">
</head>

<body >
    

    <div id="card" >
        <div class="card-body" >
            
        <div class="container" >



            <!-- Table output to be displayed from django -->
            <div class="logo-div">
                <div class="logo-text">
                    <h1> Student-Portal</h1>
                </div>
                <div class="logo-image container">
                    <img src="{% static 'assets/img/logo.png' %}" alt="" class="img-fluid">
                </div>
    
            </div>
        </div>
        <div class="text-center fs1 fw-bold mb-4 text-decoration-underline">
            <h4>Expenses incured by {{request.user.last_name|capfirst}} {{request.user.first_name|capfirst}}</h4>
        </div>
        <div id="app-table" class="container">
            {% if expenses %}
            <table class="table table-bordered border-dark">
    
                <thead>
                    <th></th>
                    <th>Description</th>
                    <th>Category</th>
                    {% if currency.currency %}
                    <th>Amount ({{currency.currency}}) </th>
                    {% else %}
                    <th>Amount</th>
                    {% endif %}
                    <th>Date</th>
    
                </thead>
                <tbody>
                    {% for expense in expenses  %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{expense.description|capfirst }}</td>
                        <td>{{expense.category.name|capfirst }}</td>
                        <td>{{expense.amount|floatformat:"2g" }}</td>
                        <td>{{expense.expense_date}}</td>
    
    
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
    
            {% endif %}
        </div>

        </div>
    
    </div>
    <div class="container btn-div">
        <button type="button" class="btn btn-success d-block" id="download-btn">Download as Pdf</button>
    </div>
    <script>
        user = "{{request.user.username}}"
    </script>








</body>

</html>

expenses/templates/expense-stats.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Expenses Summary
{% endblock title %}
{% block content %}
<style>
    .nav-add-action {
        display: flex;
        justify-content: space-between;
    }
    #card{
        width: 40rem !important;
    }
</style>

<div class="pagetitle">

    <nav class="nav-add-action">
        <div>
            <h1>Expense Summary</h1>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
                <li class="breadcrumb-item active">Expense Summary</li>
            </ol>
        </div>
    </nav>
</div><!-- End Page Title -->
{% include 'partials/_messages.html' %}
<div class="container ">
    <div class="row mt-4 mb-5">
        <div class="col-md-4">
            <p>search by specific date</p>
            <form class="d-flex" id="specific-date-form-search">
                <input type="date" name="date" id="search-by-specific-date" class="form-control">
                <input type="submit" value="search" class="btn btn-success" name="datten">
            </form>
            <div class="d-none alert mt-2" style="font-size: 12px;" role="alert" id="search-specific-date-result"></div>
        </div>
        <div class="col-md-4">

        </div>
        <div class="col-md-4 ">
            <p>search from chosen date to present</p>
            <form action="" class="d-flex" id="date-range-form-search">
                <input type="date" name="calendar" id="search-by-date-range" class="form-control">
                <input type="submit" value="search" class="btn btn-success">
            </form>
            <div class="d-none alert mt-2" style="font-size: 12px;" role="alert" id="search-specific-date-range-result">
            </div>
        </div>
    </div>
</div>
<div class="alert alert-danger d-none" role="alert" id="no-data-to-chart">
            Sorry, you have no expense data to view. Kindly create one
          </div>
<div class="container mt-5">
    <div class="row" id="card">
        
        <div class="col-lg-12" id="chartView">
            <div class="card"  id="card">
                <div class="card-body">
                   
                    <h5 class="card-title" id="card-title">Bar Chart showing expense by Category</h5>
                    <canvas id="Chart"
                        style="max-height: 400px; display: block; box-sizing: border-box; height: 59px; width: 118px;"
                        width="236" height="178"></canvas>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container pe-3 mx-3" id="chartView-btn">
    <div class="row d-flex ">
        <div class="col-md-6 ">
            <input class="btn btn-primary btn-sm" type="submit" value="Bar Chart" id="barChart">
            <input class="btn btn-secondary btn-sm" type="submit" value="Line Chart" id="lineChart">
            <input class="btn btn-success btn-sm" type="submit" value="Pie Chart" id="pieChart">
            <input class="btn btn-dark btn-sm" type="submit" value="Doughnut Chart" id="doughnutChart">
        </div>
        <div class="col-md-2 text-right">
            <input class="btn btn-info btn-sm" type="button" value="Download" id="download-btn">
        </div>
    </div>
</div>

<script src="{% static 'assets/js/expense-stats.js' %}"></script>
<script src="{% static 'assets/js/html2pdf.bundle.min.js' %}"></script>
{% endblock content %}

expenses/templates/expenses.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Expenses
{% endblock title %}
{% block content %}
<style>
    .nav-add-action {
        display: flex;
        justify-content: space-between;
    }

    .pagination {
        display: flex;
        justify-content: space-between;
    }

    .step-links {
        display: flex;
    }
</style>

<div class="pagetitle">

    <nav class="nav-add-action">
        <div>
            <h1>Expenses</h1>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
                <li class="breadcrumb-item active"> Expenses</li>
            </ol>
        </div>
        <div>
            <a class="btn button-background" href="{% url 'expenses:add-expenses' %}">Add Expense</a>
        </div>

    </nav>
    <div>
        {% include 'partials/_messages.html' %}
    </div>
    {% if expenses %}
    <div class="container row mt-4 mb-4">
        <div class="col-md-8">
            <a href="{% url 'expenses:export-pdf' %}" class="btn btn-primary btn-sm">Export to PDF</a>
            <a href="{% url 'expenses:export-csv' %}" class="btn btn-secondary btn-sm">Export to CSV</a>
          
        </div>
        <div class="col-md-4">
            <form action="" class="form-group">
                <input type="text" class="form-control" id="searchField" placeholder="Search by Category">
            </form>
        </div>
    </div>
    {% endif %}
    <!-- Table output to be displayed from django -->
    <div id="app-table">
        {% if expenses %}
        <table class="table table-stripped table-hover">

            <thead>
                <th></th>
                <th>Description</th>
                <th>Category</th>
                {% if currency.currency %}
                <th>Amount ({{currency.currency}}) </th>
                {% else %}
                <th>Amount</th>
                {% endif %}
                <th>Date</th>
                <th></th>
            </thead>
            <tbody>
                {% for expense in expenses  %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{expense.description|capfirst }}</td>
                    <td>{{expense.category.name|capfirst }}</td>
                    <td>{{expense.amount|floatformat:"2g" }}</td>
                    <td>{{expense.expense_date}}</td>

                    <td>
                        <a href="{% url 'expenses:update-expense' expense.slug %}"
                            class="btn btn-sm btn-outline-success">Edit</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        {% endif %}
    </div>
    <!--div that shows when search is not found-->
    <div id="search-not-found">
        
    </div>
    <!--Table output to be displayed when search is found using ajax -->
    <div  class="d-none mt-3"  id="table-ouput">
        <div id="random-search" ></div>
        <table class="table table-stripped table-hover">

            <thead>
                <th>Description</th>
                <th>Amount (Currency)</th>
                <th>Date</th>
            </thead>
            <tbody id="table-body">


            </tbody>
        </table>
    </div>


    {% if expenses %}
    <div class="pagination mt-4" id="pagination">
        <div>
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </span>
        </div>
        <div>
            <span class="step-links">
                {% if page_obj.has_previous %}
                <li class="page-item"><a href="?page=1" class="page-link active">1</a></li>
                <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link">Previous</a>
                </li>
                {% endif %}
                {% if page_obj.has_next %}
                <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link">Next</a>
                </li>
                <li class="page-item"><a href="?page={{ page_obj.paginator.num_pages }}"
                        class="page-link">{{ page_obj.paginator.num_pages }}</a>
                </li>
                {% endif %}
            </span>
        </div>
    </div>
    {% endif %}


</div>

</div><!-- End Page Title -->




{% block scripts %}
<script src="{% static 'assets/js/searchexpense.js' %}"></script>
{% endblock scripts %}

{% endblock content %}

expenses/templates/update-expense.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Update expenses
{% endblock title %}
{% block content %}
<style>
    .nav-add-action {
        display: flex;
        justify-content: space-between;
    }
    .errorlist{
        margin-bottom:4px;
        padding: 0px;
        list-style-type:none;
        font-weight: 500;
        color: red;
      }
</style>

<div class="pagetitle">

    <nav class="nav-add-action">
        <div>
            <h1>Update Expense</h1>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
                <li class="breadcrumb-item active">Update Expense </li>
            </ol>
        </div>
        <div class="add-action-div">
            <form action="{% url 'expenses:delete-expense' expense.slug %}" method="POST">
                {% csrf_token %}
                <button class="btn btn-danger" type="submit">Delete</button>
            </form>
        </div>
    </nav>
</div><!-- End Page Title -->
{% include 'partials/_messages.html' %}
<form class="form-group" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <div class="mt-3 text-center">
        <button type="submit" class="btn button-background">Update expense</button>
    </div>
</form>

{% endblock content %}