expenses/urls.py
from django.urls import path
from .views import (
    ExpenseView,AddExpenseView,UpdateExpenseView,
    DeleteExpenseView,SearchExpenses,expense_category_summary_json,ViewExpenseSummary,search_by_date,
    search_within_date_range,export_csv,export_pdf,ExpenseCategoryView,UpdateExpenseCategoryView
    ,AddExpenseCategoryView,DeleteExpenseCategoryView
    )

app_name = 'expenses'

urlpatterns = [

    
    path('',ExpenseView.as_view(),name='expenses'),
    path('add-expense/',AddExpenseView.as_view(),name='add-expenses'),
    path('search-expenses/',SearchExpenses,name='search-expenses'),
    path('update-expense/<slug>/',UpdateExpenseView.as_view(),name='update-expense'),
    path('delete-expense/<slug>/',DeleteExpenseView.as_view(),name='delete-expense'),
    path('expense-summary-json/',expense_category_summary_json,name='expense-category-summary-json-name'),
    path('expense-category-summary-/',ViewExpenseSummary.as_view(),name='expense-summary'),
    path('search-by-date/',search_by_date,name='search-by-date'),
    path('search-within-date/',search_within_date_range,name='search-within-date'),
    path('export-csv/',export_csv,name='export-csv'),
    path('export-pdf/',export_pdf,name='export-pdf'),
    
    
    path('categories/',ExpenseCategoryView.as_view(),name='expense-categories'),
    path('add-expense-category/',AddExpenseCategoryView.as_view(),name='add-expense-category'),
    path('update-expense-category/<slug>/',UpdateExpenseCategoryView.as_view(),name='update-expense-category'),
    path('delete-expense-category/<slug>/',DeleteExpenseCategoryView.as_view(),name='delete-expense-category'),    
]

income/urls.py
from django.urls import path
from .views import (
IncomeView,AddIncomeView,UpdateIncomeView,DeleteIncomeView,SearchIncome,ViewIncomeSummary,
 income_source_summary_json,search_by_date,search_within_date_range,export_csv,export_pdf,
 IncomeSourceView,AddIncomeSourceView,UpdateIncomeSourceView,DeleteIncomeSourceView
 )

app_name = 'income'

urlpatterns = [

    
    path('',IncomeView.as_view(),name='income'),
    path('add-income/',AddIncomeView.as_view(),name='add-income'),
    path('search-income/',SearchIncome,name='search-income'),
    path('update-income/<slug>/',UpdateIncomeView.as_view(),name='update-income'),
    path('delete-income/<slug>/',DeleteIncomeView.as_view(),name='delete-income'),
    path('income-summary-json/',income_source_summary_json,name='income-summary-json'),
    path('income-summary/',ViewIncomeSummary.as_view(),name='income-summary'),
    path('search-by-date/',search_by_date,name='search-by-date'),
    path('search-within-date/',search_within_date_range,name='search-within-date'),
    path('export-csv/',export_csv,name='export-csv'),
    path('export-pdf/',export_pdf,name='export-pdf'),
    
    
    path('sources/',IncomeSourceView.as_view(),name='sources'),
    path('add-income-source/',AddIncomeSourceView.as_view(),name='add-income-source'),
    path('update-income-source/<slug>/',UpdateIncomeSourceView.as_view(),name='update-income-source'),
    path('delete-income-source/<slug>/',DeleteIncomeSourceView.as_view(),name='delete-income-source'),


]

student_portal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from authentication.views import HomeView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('expenses/',include('expenses.urls',namespace='expenses')),
    path('accounts/',include('authentication.urls',namespace='authentication')),
    path('settings/',include('settings.urls',namespace='settings')),
    path('income/',include('income.urls',namespace='income')),
    path('profile/',include('profiles.urls',namespace='profile')),
    path('notes/',include('notes.urls',namespace='notes')),
    path('todo/',include('todo.urls',namespace='todo')),
    path('youtube/',include('youtube.urls',namespace='youtube')),
    path('books/',include('books.urls',namespace='books')),
    path('wikipedia/',include('wiki.urls',namespace='wikipedia')),
    path('dictionary/',include('dictionary.urls',namespace='dictionary')),
   
    path('',HomeView,name='home'),
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path
from .views import TodoListView,TodoCreateView,TodoUpdateView,TodoDeleteView,TodoEditView

app_name = 'todo'

urlpatterns = [
    
    path('all-todo/',TodoListView.as_view(),name='all-todos'),
    path('create-todo/',TodoCreateView.as_view(),name='create-todo'),
    path('edit-todo/<slug>/',TodoEditView,name='edit-todo'),
    path('update-todo/<slug>/',TodoUpdateView,name='update-todo'),
    path('delete-todo/<slug>/',TodoDeleteView,name='delete-todo'),
    
]

expenses/forms.py
from django.forms import ModelForm
from .models import Expense,ExpenseCategory 
from django import forms 

class ExpenseForm(ModelForm):
    
    class Meta:
        model = Expense
        fields = ['description','amount','expense_date','category']
        
    def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            
            self.fields['description'].widget.attrs.update({'class': 'form-control'})
            self.fields['amount'].widget.attrs.update({'class': 'form-control'})
            self.fields['category'].widget.attrs.update({'class': 'form-control'})
            self.fields['expense_date'].widget.attrs.update({'class': 'form-control','type':'date'})
            
class ExpenseCategoryForm(ModelForm):
    
    class Meta:
        model=ExpenseCategory
        fields = ['name']
    
    def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['name'].widget.attrs.update({'class': 'form-control'})
    
    

expenses/views.py
from django.contrib.auth.models import User
from django.http import JsonResponse, request,Http404
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic import ListView,CreateView,UpdateView,DeleteView,TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import ExpenseCategory, Expense
from django.contrib import messages
from .forms import ExpenseForm,ExpenseCategoryForm
from django.urls import reverse_lazy,reverse
from django.contrib.messages.views import SuccessMessageMixin
from django.views.decorators.http import require_http_methods
from settings.models import UserPreferences
from django.contrib.auth.decorators import login_required
import datetime,csv,json
# Create your views here.
  
class ExpenseView(LoginRequiredMixin,ListView):
    """This View lists all the expenses a user incures"""
    model = Expense
    template_name = 'expenses.html'
    context_object_name = 'expenses' 
    paginate_by = 5
    
    def get_queryset(self):
        expenses = Expense.objects.filter(owner=self.request.user)
        return expenses 
         

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # get currency of user
        currency = UserPreferences.objects.get(user=self.request.user)
        context['currency'] = currency
        
        return context
    
    

class AddExpenseView(LoginRequiredMixin,CreateView):
    """This View helps users to add expense"""
    model = Expense
    form_class = ExpenseForm
    template_name='add-expense.html'
    
    def get_context_data(self, **kwargs):
        context =  super(AddExpenseView,self).get_context_data(**kwargs)
        context['form'].fields['category'].queryset = ExpenseCategory.objects.filter(owner=self.request.user)
        return context
    
   

    
    def post(self,request,*args, **kwargs):
        form = ExpenseForm(request.POST or None)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.owner = request.user
            form.save()
            messages.success(request,'Expense has been added succesfully')
            return redirect('expenses:expenses')
        else:
            messages.error(request,'Sorry, your expense could not be added due to an errror')
            return render(request,'add-expense.html',{'form':form})
        
 
    
    
class UpdateExpenseView(LoginRequiredMixin,SuccessMessageMixin,UpdateView):
    """This View helps user Update their expenses"""
    model = Expense
    form_class = ExpenseForm
    template_name = 'update-expense.html' 
    success_message = "Expense was updated sucessfully"
    success_url =  reverse_lazy('expenses:expenses') 
    
    def get_context_data(self, **kwargs):
        context =  super(UpdateExpenseView,self).get_context_data(**kwargs)
        context['form'].fields['category'].queryset = ExpenseCategory.objects.filter(owner=self.request.user)
        return context
    
    def get_object(self, queryset=None):
        """ Hook to ensure object is owned by request.user. """
        obj = super(UpdateExpenseView, self).get_object()
        if not obj.owner == self.request.user:
            raise Http404
        return obj

    
   
    
class DeleteExpenseView(LoginRequiredMixin,DeleteView):
    """This view helps users delete expenses"""
    model = Expense
    success_url = reverse_lazy('expenses:expenses') 
    
    def get_success_url(self):
        messages.success(self.request,"Expense was deleted sucessfully")
        return reverse('expenses:expenses') 
    
    def get_object(self, queryset=None):
        """ Hook to ensure object is owned by request.user. """
        obj = super(DeleteExpenseView, self).get_object()
        if not obj.owner == self.request.user:
            raise Http404
        return obj


@login_required
@require_http_methods('POST')
def SearchExpenses(request):
    """This view helps user to search for expense by category"""
    search_str = json.loads(request.body).get('searchText') 
    expensecategory = ExpenseCategory.objects.filter(name__icontains=search_str)
    expenses = Expense.objects.filter(category__in=expensecategory,owner=request.user)
    data = expenses.values()
    return JsonResponse(list(data), safe=False)
    
@login_required
@require_http_methods('POST')   
def expense_category_summary_json(request):
    """Generates expense total amount based on category for expense summary page by default"""
    todays_date = datetime.date.today()
    six_months_ago = todays_date - datetime.timedelta(days=180)
    expenses = Expense.objects.filter(expense_date__gte=six_months_ago,expense_date__lte = todays_date,owner=request.user)
    finalrep = {}
    
    for expense in expenses:
       if  finalrep.get(expense.category.name) is not None:
           finalrep[expense.category.name]+= expense.amount
       else:
           finalrep[expense.category.name] = expense.amount
    return JsonResponse({'expense_category_data':finalrep},safe=False)


class ViewExpenseSummary(LoginRequiredMixin,TemplateView):
    """This is the default view for the expense summary page"""
    template_name = "expense-stats.html" 

@login_required
@require_http_methods('POST') 
def search_by_date(request):
    """This view helps user to search for expense incurred on a specific date"""
    date = json.loads(request.body).get('date')     
    expenses = Expense.objects.filter(expense_date=date,owner=request.user)
    finalrep = {}
    for expense in expenses:
       if  finalrep.get(expense.category.name) is not None:
           finalrep[expense.category.name]+= expense.amount
       else:
           finalrep[expense.category.name] = expense.amount
    return JsonResponse({'expense_category_data':finalrep},safe=False)


@require_http_methods('POST')
def search_within_date_range(request):
    """This view helps users search for expenses incurred with a date range eg from 2/22/2021 to current day"""
    date = json.loads(request.body).get('date')     
    todays_date = todays_date = datetime.date.today()
    expenses = Expense.objects.filter(expense_date__gte=date,expense_date__lte = todays_date,owner=request.user)
    finalrep = {}
    
    for expense in expenses:
       if  finalrep.get(expense.category.name) is not None:
           finalrep[expense.category.name]+= expense.amount
       else:
           finalrep[expense.category.name] = expense.amount
    return JsonResponse({'expense_category_data':finalrep},safe=False)

@login_required
@require_http_methods('GET')
def export_csv(request):
    """This view helps user to export expenses data as csv"""
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename=expenses'+str(request.user.username)+str(datetime.datetime.now())+'.csv'
    writer = csv.writer(response)
    writer.writerow(['Description','Category','Amount','Date'])
    
    expenses = Expense.objects.filter(owner=request.user)
    
    for expense in expenses:
        writer.writerow([expense.description,expense.category,expense.amount,expense.expense_date])
    return response


@login_required
@require_http_methods('GET')
def export_pdf(request,*args, **kwargs):
    """This view helps users to export expenses data as pdf"""
    expenses = Expense.objects.filter(owner=request.user)
    currency = UserPreferences.objects.get(user=request.user)
    return render(request,'expense-pdf-output.html',context={'expenses':expenses,'currency':currency})



#------------------------------------Income Sources-----------------------------------------------
class ExpenseCategoryView(LoginRequiredMixin,ListView):
    """Lets users view all their income sources"""
    model = ExpenseCategory
    template_name = 'expense-category/expense-category.html' 
    paginate_by = 5
    context_object_name = 'expense_categories' 
    
    def get_queryset(self):
        # Get income  sources queryset
        expense_categories =ExpenseCategory.objects.filter(owner=self.request.user)
        return expense_categories
        
class AddExpenseCategoryView(LoginRequiredMixin,CreateView):
    form_class =ExpenseCategoryForm
    template_name='expense-category/add-expense-category.html'
    
    
   
    
    def post(self,request,*args, **kwargs):
        form =ExpenseCategoryForm(request.POST or None)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.owner = request.user
            form.save()
            messages.success(request,'Expense category has been added succesfully')
            return redirect('expenses:expense-categories')
        else:
            messages.error(request,'Sorry, your expense category could not be added due to an errror')
            return render(request,'expense-category/add-expense-category.html',{'form':form})
            
            
class UpdateExpenseCategoryView(LoginRequiredMixin,SuccessMessageMixin,UpdateView):
    model = ExpenseCategory
    form_class = ExpenseCategoryForm
    template_name = 'expense-category/update-expense-category.html'
    success_message = "Expense category was updated sucessfully"
    success_url =  reverse_lazy('expenses:expense-categories') 
    
    def get_object(self, queryset=None):
        """ Hook to ensure object is owned by request.user. """
        obj = super(UpdateExpenseCategoryView, self).get_object()
        if not obj.owner == self.request.user:
            raise Http404
        return obj
    

class DeleteExpenseCategoryView(LoginRequiredMixin,SuccessMessageMixin,DeleteView):
    model =ExpenseCategory
    success_url = reverse_lazy('expenses:expense-categories') 
    
    def get_success_url(self):
        messages.success(self.request, "Expense category was deleted sucessfully")
        return reverse('expenses:expense-categories')
    
    def get_object(self, queryset=None):

expenses/templates/expense-category/add-expense-category.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Add Expense Category
{% endblock title %}
{% block content %}

<style>
    .errorlist{
        margin-bottom:4px;
        padding: 0px;
        list-style-type:none;
        font-weight: 500;
        color: red;
      }
</style>

    <div class="pagetitle">
        <h1>Add Expense Category </h1>
        <nav >
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
                <li class="breadcrumb-item active">Add Income Source</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->
    {% include 'partials/_messages.html' %}
    <form action="{% url 'income:add-income-source' %}" class="form-group" method="POST" >
        {% csrf_token %}
        {{form.as_p}}
       <div class="mt-3 text-center">
        <button type="submit" class="btn button-background">Add Income Source</button>
       </div>
    </form>
    


{% endblock content %}

expenses/templates/expense-category/expense-category.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Expense Category
{% endblock title %}
{% block content %}
<style>
    .nav-add-action {
        display: flex;
        justify-content: space-between;
    }

    .pagination {
        display: flex;
        justify-content: space-between;
    }

    .step-links {
        display: flex;
    }
</style>

<div class="pagetitle">

    <nav class="nav-add-action">
        <div>
            <h1>Expense Category</h1>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
                <li class="breadcrumb-item active"> Expense Category</li>
            </ol>
        </div>
        <div>
            <a class="btn button-background" href="{% url 'expenses:add-expense-category' %}">Add Expense Category</a>
        </div>

    </nav>
    <div>
        {% include 'partials/_messages.html' %}
    </div>
    
     {% if income_sources %}
    <div class="container row mt-3 mb-3">
        <div class="col-md-8">

        </div>
        <div class="col-md-4">
            <form action="" class="form-group">
                <input type="text" class="form-control" id="searchField" placeholder="Search Income by Category">
            </form>
        </div>
    </div>
    {% endif %}
    <!-- Table output to be displayed from django -->
    <div id="app-table">
        {% if expense_categories %}
        <table class="table table-stripped table-hover">

            <thead>
                <th>S/N</th>
                <th>Source Name</th>               
                <th>Created</th>
                <th>Action</th>
                <th>Action</th>
            </thead>
            <tbody>
                {% for expense in expense_categories  %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{expense.name|capfirst }}</td>
                    <td>{{expense.created|date:"D d M Y" }}</td>
                    <td>
                        <a href="{% url 'expenses:update-expense-category' expense.slug %}" class="btn btn-sm btn-outline-success">Edit</a>
                    </td>
                    <td>
                        <form action="{% url 'expenses:delete-expense-category' expense.slug %}" method="POST">
                            {% csrf_token %}
                            <button class="btn btn-sm btn-outline-danger" type="submit" >Delete</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        {% endif %}
    </div>
    <!--Div that shows when ajax result is not found-->
    <div id="search-not-found">
        
    </div>
    <!--Table output to be displayed when search is found using ajax -->
    <div  class="d-none mt-3"  id="table-ouput">
        <div id="random-search" ></div>
        <table class="table table-stripped table-hover">

            <thead>
                <th>Description</th>
                <th>Amount (Currency)</th>
                <th>Date</th>
                
            </thead>
            <tbody id="table-body">


            </tbody>
        </table>
    </div>


    {% if income_sources %}
    <div class="pagination mt-4" id="pagination">
        <div>
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </span>
        </div>
        <div>
            <span class="step-links">
                {% if page_obj.has_previous %}
                <li class="page-item"><a href="?page=1" class="page-link active">1</a></li>
                <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link">Previous</a>
                </li>
                {% endif %}
                {% if page_obj.has_next %}
                <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link">Next</a>
                </li>
                <li class="page-item"><a href="?page={{ page_obj.paginator.num_pages }}"
                        class="page-link">{{ page_obj.paginator.num_pages }}</a>
                </li>
                {% endif %}
            </span>
        </div>
    </div>
    {% endif %}



</div>

</div><!-- End Page Title -->






{% endblock content %}

expenses/templates/expense-category/update-expense-category.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Update Income Source
{% endblock title %}
{% block content %}
<style>
    .nav-add-action {
        display: flex;
        justify-content: space-between;
    }
    .errorlist{
        margin-bottom:4px;
        padding: 0px;
        list-style-type:none;
        font-weight: 500;
        color: red;
      }
</style>

<div class="pagetitle">

    <nav class="nav-add-action">
        <div >
            <h1>Update Expense Category</h1>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
                <li class="breadcrumb-item active">Update Income Source </li>
            </ol>
        </div>
    </nav>
</div><!-- End Page Title -->
{% include 'partials/_messages.html' %}
<form class="form-group" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <div class="mt-3 text-center">
        <button type="submit" class="btn button-background">Update Income Source</button>
    </div>
</form>




{% endblock content %}